import type { Metadata } from "next";
import "./globals.css";
import { workSans, funnelDisplay } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`fade-in ${workSans.variable} ${workSans.className} {${funnelDisplay.variable} antialiased}`}
      >
        {children}
      </body>
    </html>
  );
}
